version: '3.8'
services:
  ollama-telegram:
    image: ruecat/ollama-telegram
    container_name: ollama-telegram-x
    restart: always
    env_file:
      - stack.env
      # this is meant for portainer. change to ./.env for docker
  
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server-x
    volumes:
      - ./ollama:/root/.ollama
    
    # Uncomment to enable NVIDIA GPU
    # Otherwise runs on CPU only:

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    restart: always
    ports:
      - '11434:11434'
